export const onRequestGet: PagesFunction = async () => {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Product Ranker AI</title>
  <style>
    :root{--bg:#060b16;--panel:rgba(15,24,46,.76);--line:rgba(255,255,255,.08);--soft:rgba(255,255,255,.05);--text:#eef4ff;--muted:#9fb0d1;--gold:#ffd36f;--blue:#7ca0ff;--mint:#67efc0;--danger:#ff7e92;--success:#37d39f}
    *{box-sizing:border-box} html,body{margin:0;padding:0} body{font-family:Inter,Segoe UI,Roboto,Arial,sans-serif;background:radial-gradient(circle at 5% 0%,rgba(124,160,255,.18),transparent 26%),radial-gradient(circle at 100% 8%,rgba(103,239,192,.14),transparent 24%),linear-gradient(180deg,#0a1223 0%,#050912 100%);color:var(--text)} a{text-decoration:none;color:inherit}
    .container{max-width:1320px;margin:0 auto;padding:0 18px}.nav{display:flex;justify-content:space-between;align-items:center;padding:20px 0;gap:18px;position:sticky;top:0;z-index:20;background:rgba(6,11,22,.58);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.04)}.brand{display:flex;align-items:center;gap:12px;font-weight:800}.brand-badge{width:42px;height:42px;border-radius:14px;background:linear-gradient(135deg,var(--blue),var(--mint));display:grid;place-items:center;color:#04111f;font-weight:900}.nav-links{display:flex;gap:14px;align-items:center;flex-wrap:wrap}.nav-link{font-size:14px;color:var(--muted)}
    .btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;border:0;border-radius:16px;padding:13px 18px;font-weight:700;cursor:pointer;transition:.24s ease}.btn:hover{transform:translateY(-2px)}.btn-primary{background:linear-gradient(135deg,var(--gold),#ffae45);color:#091423}.btn-secondary{background:rgba(255,255,255,.05);border:1px solid var(--line);color:var(--text)}
    .hero{padding:36px 0 22px}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:22px;align-items:end}.pill{display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;background:rgba(255,255,255,.05);border:1px solid var(--line);font-size:13px;color:#d8e5ff}h1{font-size:clamp(38px,5vw,64px);line-height:1.03;margin:16px 0 12px}.lead{font-size:17px;line-height:1.75;color:var(--muted)}
    .panel,.metric-card,.rank-card,.rank-row,.summary-box{background:var(--panel);border:1px solid var(--line);backdrop-filter:blur(10px);border-radius:26px}.panel,.rank-card{padding:18px}.metric-grid,.summary-grid,.rank-metrics{display:grid;gap:12px}.metric-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.metric-card{padding:16px}.metric-card strong,.summary-box strong,.mini-box strong{display:block;font-size:28px;color:var(--gold)}.metric-card span,.summary-box span,.mini-box span{display:block;color:var(--muted);font-size:13px;margin-top:5px}
    .section{padding:18px 0 30px}.section-head h2{margin:0;font-size:30px}.section-head p{margin:8px 0 0;color:var(--muted);line-height:1.7}.rank-layout{display:grid;grid-template-columns:420px 1fr;gap:18px;align-items:start}.field{display:grid;gap:8px;margin-bottom:14px}.field label{font-size:13px;color:#d8e5ff}.field textarea{width:100%;padding:14px 16px;border-radius:16px;border:1px solid var(--line);background:#091324;color:var(--text);font-size:15px;min-height:220px;resize:vertical}.toolbar{display:flex;gap:10px;flex-wrap:wrap}.helper,.status,.why{color:var(--muted);line-height:1.7}.status{padding:14px 16px;border-radius:18px;background:rgba(255,255,255,.04);border:1px solid var(--line);margin-top:14px}.summary-grid{grid-template-columns:repeat(4,minmax(0,1fr));margin-top:14px}.summary-box{padding:14px;text-align:center}.rank-results{display:grid;gap:14px}.rank-row{padding:18px;position:relative;overflow:hidden}.rank-row::before{content:'';position:absolute;top:0;left:0;right:0;height:4px;background:linear-gradient(90deg,var(--gold),var(--danger))}.top-row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;margin-bottom:10px}.score{display:inline-flex;padding:7px 12px;border-radius:999px;background:rgba(255,211,111,.12);border:1px solid rgba(255,211,111,.24);color:#ffe5aa;font-size:12px;font-weight:800}.rec{display:inline-flex;padding:7px 12px;border-radius:999px;font-size:12px;font-weight:800}.rec.buy{background:rgba(55,211,159,.14);border:1px solid rgba(55,211,159,.24);color:#bdf6e1}.rec.watch{background:rgba(124,160,255,.14);border:1px solid rgba(124,160,255,.24);color:#d3e0ff}.rec.reject{background:rgba(255,126,146,.14);border:1px solid rgba(255,126,146,.24);color:#ffd3da}.rank-row h3{margin:0 0 6px;font-size:22px}.rank-metrics{grid-template-columns:repeat(3,minmax(0,1fr));margin:16px 0}.mini-box{padding:12px;border-radius:16px;background:var(--soft);border:1px solid rgba(255,255,255,.05);text-align:center}.empty{padding:28px;border-radius:22px;background:rgba(255,255,255,.03);border:1px dashed rgba(255,255,255,.12);text-align:center;color:var(--muted)}
    @media (max-width:1100px){.hero-grid,.rank-layout{grid-template-columns:1fr}.metric-grid,.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}} @media (max-width:640px){h1{font-size:40px}.metric-grid,.rank-metrics,.summary-grid{grid-template-columns:1fr 1fr}.nav{position:static;flex-direction:column;align-items:flex-start}}
  </style>
</head>
<body>
  <div class="container">
    <nav class="nav">
      <div class="brand"><div class="brand-badge">R</div><div>Product Ranker AI</div></div>
      <div class="nav-links"><a class="nav-link" href="/">Home</a><a class="nav-link" href="/viral.html">Viral Dashboard</a><a class="btn btn-primary" href="/viral.html">Open Viral Dashboard</a></div>
    </nav>
    <section class="hero">
      <div class="hero-grid">
        <div><div class="pill">Python scoring logic translated into site-native analysis</div><h1>Rank product candidates directly inside the site dashboard.</h1><p class="lead">Paste CSV-style candidates and get ranked outputs using margin, shipping, trend, competition, problem-solving, wow factor, and policy-risk scoring — all without any external Python server.</p></div>
        <div class="panel"><div class="metric-grid"><div class="metric-card"><strong id="sumCandidates">0</strong><span>Candidates</span></div><div class="metric-card"><strong id="sumTest">0</strong><span>TEST NOW</span></div><div class="metric-card"><strong id="sumWatch">0</strong><span>WATCHLIST</span></div><div class="metric-card"><strong id="sumReject">0</strong><span>REJECT</span></div></div></div>
      </div>
    </section>
    <section class="section"><div class="rank-layout"><aside class="rank-card"><div class="field"><label for="candidateInput">Candidates CSV</label><textarea id="candidateInput" placeholder="keyword,source,cost,sell_price,estimated_weight_kg,competition_level,problem_solving_score,wow_score,notes\npet hair remover roller,seed,4.2,19.99,0.18,5,9,7,Before/after creative possible"></textarea></div><div class="toolbar"><button class="btn btn-primary" id="analyzeBtn">Analyze Candidates</button><button class="btn btn-secondary" id="loadSampleBtn">Load Sample</button></div><p class="helper" style="margin-top:14px">Columns: keyword, source, cost, sell_price, estimated_weight_kg, competition_level, problem_solving_score, wow_score, notes</p><div id="rankerStatus" class="status">Ready to rank product candidates.</div></aside><div><div id="rankerResults" class="rank-results"></div></div></div></section>
  </div>
  <script>
    function esc(v){ return String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
    function updateSummary(summary, count){ document.getElementById('sumCandidates').textContent = count || 0; document.getElementById('sumTest').textContent = summary?.test_now || 0; document.getElementById('sumWatch').textContent = summary?.watchlist || 0; document.getElementById('sumReject').textContent = summary?.reject || 0; }
    function renderRankResults(items){ const root = document.getElementById('rankerResults'); if(!items.length){ root.innerHTML = '<div class="empty">No ranked candidates yet.</div>'; return; } root.innerHTML = items.map((item, idx) => { const recClass = item.recommended_action === 'TEST NOW' ? 'buy' : item.recommended_action === 'WATCHLIST' ? 'watch' : 'reject'; return '<article class="rank-row"><div class="top-row"><div><span class="score">#' + (idx+1) + ' • Final score ' + item.final_score + '</span></div><span class="rec ' + recClass + '">' + item.recommended_action + '</span></div><h3>' + esc(item.keyword) + '</h3><div class="rank-metrics"><div class="mini-box"><strong>' + item.trend_score + '</strong><span>Trend</span></div><div class="mini-box"><strong>' + item.margin_score + '</strong><span>Margin</span></div><div class="mini-box"><strong>' + item.shipping_score + '</strong><span>Shipping</span></div></div><div class="rank-metrics"><div class="mini-box"><strong>' + item.problem_solving_score + '</strong><span>Problem</span></div><div class="mini-box"><strong>' + item.wow_score + '</strong><span>Wow</span></div><div class="mini-box"><strong>' + item.competition_score + '</strong><span>Competition</span></div></div><div class="rank-metrics"><div class="mini-box"><strong>' + item.policy_score + '</strong><span>Policy</span></div><div class="mini-box"><strong>' + item.estimated_margin_pct + '%</strong><span>Est. margin</span></div><div class="mini-box"><strong>' + item.trend_growth_pct + '%</strong><span>Trend growth</span></div></div><div class="why"><strong style="color:#ffe2a0">Why:</strong> ' + item.reasons.join(' • ') + '</div>' + (item.notes ? '<div class="why" style="margin-top:8px"><strong style="color:#ffe2a0">Notes:</strong> ' + esc(item.notes) + '</div>' : '') + '</article>'; }).join(''); }
    async function loadSample(){ try { const response = await fetch('/api/product-ranker'); const data = await response.json(); const csv = ['keyword,source,cost,sell_price,estimated_weight_kg,competition_level,problem_solving_score,wow_score,notes', ...(data.candidates || []).map(c => [c.keyword,c.source||'manual',c.cost??'',c.sell_price??'',c.estimated_weight_kg??'',c.competition_level??'',c.problem_solving_score??'',c.wow_score??'',c.notes||''].join(','))].join('\n'); document.getElementById('candidateInput').value = csv; updateSummary({ test_now: data.analyses.filter(x => x.recommended_action === 'TEST NOW').length, watchlist: data.analyses.filter(x => x.recommended_action === 'WATCHLIST').length, reject: data.analyses.filter(x => x.recommended_action === 'REJECT').length }, data.analyses.length); renderRankResults(data.analyses || []); document.getElementById('rankerStatus').textContent = 'Loaded sample candidates and ranked them successfully.'; } catch (e) { document.getElementById('rankerStatus').textContent = 'Could not load sample ranker data.'; } }
    async function analyze(){ const csv = document.getElementById('candidateInput').value; const status = document.getElementById('rankerStatus'); status.textContent = 'Analyzing candidates...'; try { const response = await fetch('/api/product-ranker', { method:'POST', headers:{ 'content-type':'application/json' }, body: JSON.stringify({ csv }) }); const data = await response.json(); updateSummary(data.summary, data.candidate_count); renderRankResults(data.analyses || []); status.textContent = 'Ranking complete. ' + data.candidate_count + ' candidates processed.'; } catch (e) { status.textContent = 'Could not rank the candidates right now.'; } }
    document.getElementById('analyzeBtn').addEventListener('click', analyze); document.getElementById('loadSampleBtn').addEventListener('click', loadSample); loadSample();
  </script>
</body>
</html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=UTF-8', 'cache-control': 'no-store' } });
};